server:
  port: 9004
spring:
  application:
    name: ten-article
  jackson:
    default-property-inclusion: non_null  #s 过滤响应时候的空字段,不在前端显示
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      stat-view-servlet:
        login-username: admin
        login-password: 123456
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.27.237.3:3306/tensquare_article?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
 # mongodb
  data:
    mongodb:
      host: 192.168.73.128
      port: 27017
      database: commentdb
  redis:
    host: 120.27.237.3
    port: 6379
mybatis:
  mapper-locations: classpath:/mapper/*.xml
