server:
  port: 6868
spring:
  application:
    name: ten-eureka
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:${server.port}/eureka
    registry-fetch-interval-seconds: 5
    # 是否将自己注册进eureka
    register-with-eureka: false
    # 是否从eureka中获取信息
    fetch-registry: false
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}