server:
  port: 9001
spring:
  application:
    name: ten-base
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.27.237.3:3306/tensquare_base?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      stat-view-servlet:
        login-username: admin
        login-password: 123456
  jpa:
    show-sql: true
    database: mysql
mybatis:
  mapper-locations: classpath:/mapper/*.xml

pagehelper:
  helper-dialect: mysql
  support-methods-arguments: true

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka
    registry-fetch-interval-seconds: 5
    # 是否将自己注册进eureka
    register-with-eureka: true
    # 是否从eureka中获取信息
    fetch-registry: true
  instance:
    # 发现ip
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}

